<!DOCTYPE html>
<html lang="fr">

<head>
    <?php include_once('view/include/head.html'); ?>
    <?php if ($_SESSION["snow"] === true) : ?>
    <script src="./library/js/snow.js"></script>
    <?php endif ?>
    <title>Développeur Web, Infographiste sur Paris - Pierre Marquet</title>
</head>

<body>

    <?php include_once('view/include/nav.html'); ?>

    <main class="container">
        <!-- profile and logo -->
        <div class="profile">
            <img class="rounded-circle" id="profilePicture" src="./sources/files/profile.jpg" alt="Pierre Marquet"
                width="200" height="200">
            <div class="ml-5 mr-5">
                <h2 id="name">Pierre Marquet</h2>
                <h1 id="job">Infographiste / Développeur Web</h1>
                <h3><i class="fas fa-map-marker-alt"></i> Paris</h3>
            </div>
            <img src="./sources/files/logoBl.png" alt="Infographie logo" class="todisappear" id="logo" height="200">
        </div>

        <!-- description -->
        <div class="mt-3">
            <p class="text-justify text-dark">
                Issu du monde de l'<strong>infographie</strong>, j'ai travaillé pendant 5 ans pour la
                <strong>Gendarmerie Nationale</strong> afin de met tre en forme des parcours d'enseignements grâce
                à de l'<strong>image</strong> et l'<strong>animation</strong>, avant d’effectuer une formation de
                <strong>développeur web et web mobile</strong> dans le but de devenir plus polyvalent.
            </p>
            <p class="text-justify text-dark">
                Actuellement je suis à recherche d'une alternance pour mon <strong>Bachelor 3 en développement</strong>
                au sein de <strong>Sup de Vinci</strong> afin de continuer dans ce domaine qui me passionne.
                Rythme 15j/15j
            </p>
        </div>

        <!-- technology and software -->
        <div id="techs" class="d-flex">
            <div>
                <h5>logiciels</h5>
                <p><img src="./sources/files/tech_icons/illustrator.png" alt="logo Illustrator"> Adobe Illustrator</p>
                <p><img src="./sources/files/tech_icons/photoshop.png" alt="logo Photoshop"> Adobe Photoshop</p>
                <p><img src="./sources/files/tech_icons/indesign.png" alt="logo indesign"> Adobe Indesign</p>
                <p><img src="./sources/files/tech_icons/vscode.png" alt="logo Visual Studio Code"> Visual Studio Code
                </p>
                <p><img src="./sources/files/tech_icons/jmerise.png" alt="logo Jmerise"> Jmerise</p>
                <p><img src="./sources/files/tech_icons/bouml.png" alt="logo BoUML"> BoUML</p>
            </div>
            <div>
                <h5>Langages</h5>
                <p><img src="./sources/files/tech_icons/html.png" alt="logo html5"> HTML 5</p>
                <p><img src="./sources/files/tech_icons/css.png" alt="logo css3"> CSS 3</p>
                <p><img src="./sources/files/tech_icons/javascript.png" alt="logo javascript"> Javascript</p>
                <p><img src="./sources/files/tech_icons/php.png" alt="logo php"> PHP</p>
            </div>
            <div>
                <h5>Frameworks / Libraries</h5>
                <p><img src="./sources/files/tech_icons/symfony.png" alt="logo symfony"> Symfony</p>
                <p><img src="./sources/files/tech_icons/jquery.png" alt="logo jquery"> jQuery</p>
                <p><img src="./sources/files/tech_icons/bootstrap.png" alt="logo bootstrap"> Bootstrap</p>
            </div>
            <div>
                <h5>CMS</h5>
                <p><img src="./sources/files/tech_icons/wordpress.png" alt="logo wordpress"> Wordpress</p>
                <p><img src="./sources/files/tech_icons/drupal.png" alt="logo drupal"> Drupal</p>
                <p><img src="./sources/files/tech_icons/prestashop.png" alt="logo prestashop"> Prestashop</p>
            </div>
            <div>
                <h5>SGBD</h5>
                <p><img src="./sources/files/tech_icons/mysql.png" alt="logo MySQL"> MySQL</p>
                <p><img src="./sources/files/tech_icons/posgresql.png" alt="logo PosgreSQL"> PosgreSQL</p>
                <p><img src="./sources/files/tech_icons/sqlserver.png" alt="logo SQLserver"> SQLserver</p>
            </div>
        </div>

        <!-- links -->
        <div class="d-flex flex-wrap justify-content-center">
            <a href="https://www.linkedin.com/in/pierre-marquet-98987b199/"
                onclick="window.open(this.href); return false;" class="link btn btn-primary btn-lg"><i
                    class="fab fa-linkedin-in"></i> | Voir mon linkedin</a>
            <a href="https://github.com/SokouPM" onclick="window.open(this.href); return false;"
                class="link btn btn-secondary btn-lg "><i class="fab fa-github"></i> | Voir mon github</a>
            <a href="index.php?contact" class="link btn btn-danger btn-lg"><i class="fa fa-envelope"></i> |
                Contactez-moi</a>
            <a href="./sources/files/CV_PierreMarquet.pdf" onclick="window.open(this.href); return false;"
                class="link btn btn-success btn-lg"><i class="fas fa-file-pdf"></i> | Téléchargez mon CV</a>
        </div>

        <!-- carousel -->
        <div id="carouselSlide" class="carousel slide mt-5" data-ride="carousel">
            <ul class="carousel-indicators">
                <li data-target="#carouselSlide" data-slide-to="0" class="active"></li>
                <li data-target="#carouselSlide" data-slide-to="1"></li>
                <li data-target="#carouselSlide" data-slide-to="2"></li>
                <li data-target="#carouselSlide" data-slide-to="3"></li>
            </ul>
            <!-- carousel pictures -->
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="./sources/carousel/1.png" alt="site web teamrocket" height="600">
                </div>
                <div class="carousel-item">
                    <img src="./sources/carousel/2.png" alt="infographie jaquette" height="600">
                </div>
                <div class="carousel-item">
                    <img src="./sources/carousel/3.png" alt="infographie livret" height="600">
                </div>
                <div class="carousel-item">
                    <img src="./sources/carousel/4.png" alt="photomontage" height="600">
                </div>
            </div>
            <!-- carousel controls -->
            <a class="carousel-control-prev" href="#carouselSlide" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#carouselSlide" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>

    </main>

    <?php include_once('view/include/footer.html'); ?>

</body>

</html>