<!DOCTYPE html>
<html lang="fr">

<head>
    <?php include_once('view/include/head.html'); ?>
    <?php if ($_SESSION["snow"] === true) : ?>
        <script type="text/javascript" src="./library/js/snow.js"></script>
    <?php endif ?>
    <title>Contact - Pierre Marquet</title>
</head>

<body>

    <?php include_once('view/include/nav.html'); ?>

    <main class="container">
        <h1 class="mb-5 text-center">Me contacter</h1>
        <form action="index.php?contactPost" method="POST">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="lastName">Nom :</label>
                    <input type="text" class="form-control" name="lastName" pattern="^[A-Za-zÀ-ÿ]{2,50}" placeholder="Votre nom" <?php if (isset($_SESSION["lastName"])) : echo "value=\"" . $_SESSION["lastName"] . "\""; endif; ?> required="required">
                </div>
                <div class="form-group col-md-6">
                    <label for="firstName">Prénom :</label>
                    <input type="text" class="form-control" name="firstName" pattern="^[A-Za-zÀ-ÿ]{2,50}" placeholder="Votre prénom" <?php if (isset($_SESSION["firstName"])) : echo "value=\"" . $_SESSION["firstName"] . "\""; endif; ?> required="required">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="email">Courriel :</label>
                    <input type="email" class="form-control" name="email" pattern="[a-z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}" placeholder="example@mail.com" <?php if (isset($_SESSION["email"])) : echo "value=\"" . $_SESSION["email"] . "\""; endif; ?> required="required">
                </div>
                <div class="form-group col-md-6">
                    <label for="object">Objet :</label>
                    <input type="text" class="form-control" name="object" placeholder="L'objet de votre message" <?php if (isset($_SESSION["object"])) : echo "value=\"" . $_SESSION["object"] . "\""; endif; ?> required="required">
                </div>
            </div>
            <div class="form-group">
                <label for="message">Message :</label>
                <textarea class="form-control" name="message" placeholder="Votre message..." rows="10" required="required"><?php if (isset($_SESSION["message"])) : echo ($_SESSION["message"]); endif; ?></textarea>
            </div>
            <div class="text-center">

                <?php if (isset($_SESSION["mailReturn"]) && isset($_SESSION["mailConfirm"])) : ?>
                    <p class="font-weight-bold <?php if ($_SESSION["mailConfirm"] == true) : echo "text-success"; else : echo "text-danger"; endif; ?>"><?php echo ($_SESSION["mailReturn"]) ?></p>

                    <?php $_SESSION["mailReturn"]   = null; ?>
                    <?php $_SESSION["mailConfirm"]  = null; ?>
                    <?php $_SESSION["lastName"]     = null; ?>
                    <?php $_SESSION["firstName"]    = null; ?>
                    <?php $_SESSION["email"]        = null; ?>
                    <?php $_SESSION["object"]       = null; ?>
                    <?php $_SESSION["message"]      = null; ?>
                <?php endif; ?>

                <button type="submit" class="btn btn-primary btn-lg formLink">Envoyer</button>
                <button type="reset" class="btn btn-danger btn-lg formLink">Effacer</button>
            </div>
        </form>
    </main>

    <?php include_once('view/include/footer.html'); ?>

</body>

</html>