<!DOCTYPE html>
<html lang="fr">

<head>
    <?php include_once('view/include/head.html'); ?>
    <title>Productions web - Pierre Marquet</title>
</head>

<body>

    <?php include_once('view/include/nav.html'); ?>

    <main class="container">
        <h1 class="mb-5 text-center">Me contacter</h1>
        <form action="index.php?contactPost" method="POST">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="lastName">Nom</label>
                    <input type="text" class="form-control" name="lastName" pattern="^[A-Za-z]{2,50}" placeholder="Marquet" required>
                </div>
                <div class="form-group col-md-6">
                    <label for="firstName">Prénom</label>
                    <input type="text" class="form-control" name="firstName" pattern="^[A-Za-z]{2,30}" placeholder="Pierre" required>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="email">Courriel</label>
                    <input type="email" class="form-control" name="email" pattern="[a-z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}" placeholder="example@gmail.com" required>
                </div>
                <div class="form-group col-md-6">
                    <label for="object">Objet</label>
                    <input type="text" class="form-control" name="object" placeholder="L'objet de votre message" required>
                </div>
            </div>
            <div class="form-group">
                <label for="message">Message</label>
                <textarea class="form-control" name="message" placeholder="Votre message..." rows="10" required></textarea>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-primary btn-lg formLink">Envoyer</button>
                <button type="reset" class="btn btn-danger btn-lg formLink">Effacer</button>
            </div>
        </form>
    </main>

    <?php include_once('view/include/footer.html'); ?>

</body>

</html>