<!DOCTYPE html>
<html lang="fr">

<head>
    <?php include_once './view/include/head.html' ?>
</head>

<body>
    
    <main id="home" class="container d-flex justify-content-center align-items-stretch">
        <a href="whoami" class="container d-flex justify-content-center flex-column" id="goOnSite">

            <?php include_once './view/include/logoAnim.svg' ?>

            <div class="todisappear">
                <h1 id="welcomeTitle" class="text-center font-weight-bold">Bienvenue</h1>
                <h2 id="clickToGo" class="text-center font-weight-bold font-italic">Cliquez pour entrer</h2>
            </div>

        </a>
    </main>
    <script src="/MyWebSite/library/js/animation.js"></script>
</body>

</html>