<!DOCTYPE html>
<html lang="fr">

<head>
    <?php include_once('include/head.html'); ?>
    <?php if ($_SESSION["snow"] === true) : ?>
        <script src="./library/js/snow.js"></script>
    <?php endif ?>
    <title>Développeur Web, Infographiste sur Paris - Pierre Marquet</title>
</head>

<body>

    <main id="home" class="container d-flex justify-content-center align-items-stretch">
        <a href="index.php?presentation" class="container d-flex justify-content-center flex-column" id="goOnSite">

            <?php include_once('view/include/logoAnim.svg'); ?>

            <div>
                <h1 id="welcomeTitle" class="text-center font-weight-bold">Bienvenue</h1>
                <h2 id="clickToGo" class="text-center font-weight-bold font-italic">Cliquez pour entrer</h2>
            </div>

        </a>
    </main>
    <script src="./library/js/animation.js"></script>
</body>

</html>