<!DOCTYPE html>
<html lang="fr">

<head>
<?php include_once './view/include/head.html' ?>
</head>

<body>

    <?php include_once './view/include/nav.html' ?>

    <main class="container">
        <h1 class="text-center">Mes productions graphiques</h1>
        <p class="mb-4 text-center font-italic">Cliquez un élément pour l'agrandir</p>
        <div class=" d-flex flex-wrap justify-content-center">
            <div class="production">
                <a href="./sources/infographics/Jaquette60AnsSecoursEnMontagne.pdf" onclick="window.open(this.href); return false;"><img src="./sources/infographics/Jaquette60AnsSecoursEnMontagne.jpg" alt="Lien vers infographie"></a>
                <p class="workTitle">Jaquette DVD 60 ans secours en montagne</p>
            </div>
            <div class="production">
                <a href="./sources/infographics/JaquetteEUPST.pdf" onclick="window.open(this.href); return false;"><img src="./sources/infographics/JaquetteEUPST.jpg" alt="Lien vers infographie"></a>
                <p class="workTitle">Jaquette DVD EUSPT II</p>
            </div>
            <div class="production">
                <a href="./sources/infographics/JaquetteHommageAuxMorts.pdf" onclick="window.open(this.href); return false;"><img src="./sources/infographics/JaquetteHommageAuxMorts.jpg" alt="Lien vers infographie"></a>
                <p class="workTitle">Jaquette DVD Hommage aux morts</p>
            </div>
            <div class="production">
                <a href="./sources/infographics/CompoPointFortFichet.pdf" onclick="window.open(this.href); return false;"><img src="./sources/infographics/CompoPointFortFichet.jpg" alt="Lien vers infographie"></a>
                <p class="workTitle">Compo graphique Point fort fichet</p>
            </div>
            <div class="production">
                <a href="./sources/infographics/RetouchePhotoSnoopDog.jpg" onclick="window.open(this.href); return false;"><img src="./sources/infographics/RetouchePhotoSnoopDog.jpg" alt="Lien vers infographie"></a>
                <p class="workTitle">Retouche photo Snoop Dog</p>
            </div>
            <div class="production">
                <a href="./sources/infographics/RetouchePhotoDarkVador.jpg" onclick="window.open(this.href); return false;"><img src="./sources/infographics/RetouchePhotoDarkVador.jpg" alt="Lien vers infographie"></a>
                <p class="workTitle">Retouche photo Dark Vador</p>
            </div>
            <div class="production">
                <a href="./sources/infographics/CartedeVisiteAquaService.pdf" onclick="window.open(this.href); return false;"><img src="./sources/infographics/CartedeVisiteAquaService.jpg" alt="Lien vers infographie"></a>
                <p class="workTitle">Carte de visite Aqua Service</p>
            </div>
            <div class="production">
                <a href="./sources/infographics/CartedeVisiteComGaudry.pdf" onclick="window.open(this.href); return false;"><img src="./sources/infographics/CartedeVisiteComGaudry.jpg" alt="Lien vers infographie"></a>
                <p class="workTitle">Carte de visite Com.Gaudry</p>
            </div>
            <div class="production">
                <a href="./sources/infographics/LivretCPMGN.pdf" onclick="window.open(this.href); return false;"><img src="./sources/infographics/LivretCPMGN.jpg" alt="Lien vers infographie"></a>
                <p class="workTitle">Livret accueil CPMGN</p>
            </div>
            <div class="production">
                <a href="./sources/infographics/FlyerFestivalNevian.pdf" onclick="window.open(this.href); return false;"><img src="./sources/infographics/FlyerFestivalNevian.jpg" alt="Lien vers infographie"></a>
                <p class="workTitle">Flyer festival de Nevian</p>
            </div>
            <div class="production">
                <a href="./sources/infographics/FlyerPatineEtCo.pdf" onclick="window.open(this.href); return false;"><img src="./sources/infographics/FlyerPatineEtCo.jpg" alt="Lien vers infographie"></a>
                <p class="workTitle">Flyer Patines & Cie</p>
            </div>
            <div class="production">
                <a href="./sources/infographics/MenuChampaAsie.pdf" onclick="window.open(this.href); return false;"><img src="./sources/infographics/MenuChampaAsie.jpg" alt="Lien vers infographie"></a>
                <p class="workTitle">Menu restaurant Champa d'Asie</p>
            </div>
            <div class="production">
                <a href="./sources/infographics/FlyerStephCoifure.pdf" onclick="window.open(this.href); return false;"><img src="./sources/infographics/FlyerStephCoifure.jpg" alt="Lien vers infographie"></a>
                <p class="workTitle">Flyer Steph'coifure</p>
            </div>
            <div class="production">
                <a href="./sources/infographics/FlyerLeTantra.pdf" onclick="window.open(this.href); return false;"><img src="./sources/infographics/FlyerLeTantra.jpg" alt="Lien vers infographie"></a>
                <p class="workTitle">Flyer club Le tantra</p>
            </div>
            <div class="production">
                <a href="./sources/infographics/FlyerSecretsDeSiege.pdf" onclick="window.open(this.href); return false;"><img src="./sources/infographics/FlyerSecretsDeSiege.jpg" alt="Lien vers infographie"></a>
                <p class="workTitle">Flyer Atelier secrets de siège</p>
            </div>
            <div class="production">
                <a href="./sources/infographics/LivretSibarite.pdf" onclick="window.open(this.href); return false;"><img src="./sources/infographics/LivretSibarite.jpg" alt="Lien vers infographie"></a>
                <p class="workTitle">Dossier boutique Sibarite</p>
            </div>
        </div>
    </main>

    <?php include_once './view/include/footer.html' ?>

</body>

</html>