<!DOCTYPE html>
<html lang="fr">

<head>
<?php include_once './view/include/head.html' ?>
</head>

<body>

    <?php include_once './view/include/nav.html' ?>

    <main class="container bigtext">
        <h1 class="mb-5 text-center">Mon parcours</h1>
        <table class="container-fluid">
            <tr class="align-top">
                <td class="text-right">Novembre <span class="text-primary">2019</span> - Juillet <span class="text-primary">2020</span></td>
                <td class="smaller">....</td>
                <td>Formation Développeur web et web mobile - AFPA de Balma (31)</td>
            </tr>
            <tr class="align-top">
                <td class="text-right">Mai - Juillet <span class="text-primary">2020</span></td>
                <td class="smaller">....</td>
                <td><span class="text-danger">Développeur web et web mobile</span></td>
            </tr>
            <tr class="align-top">
                <td colspan="2"></td>
                <td class="pb-4"><a href="diploma!!!!!!!!!!!!!!!!" onclick="window.open(this.href); return false;" class="link btn btn-info"><i class="fa fa-file"> | Titre de développeur web et web mobile</i></a></td>
            </tr>
            <tr class="align-top">
                <td class="text-right">Septembre <span class="text-primary">2014</span> - Octobre <span class="text-primary">2019</span></td>
                <td class="smaller">....</td>
                <td><span class="text-danger">Infographiste</span> / <span class="text-danger">Gendarme Adjoint volontaire</span> - Centre de Production Multimédia de la GN à Limoges (31)</td>
            </tr>
            <tr class="align-top">
                <td colspan="2"></td>
                <td class="pb-4"><img src="./sources/files/logoGendarmerie.jpg" alt="Logo gendarmerie Nationale" width="200"></td>
            </tr>
            <tr class="align-top">
                <td class="text-right">Septembre<span class="text-primary">2013</span> - Juillet <span class="text-primary">2014</span></td>
                <td class="smaller">....</td>
                <td>1ère année BTS Design d'espace et volume - Lycée J.F. Champollion à Montpellier (34)</td>
            </tr>
            <tr class="align-top">
                <td class="pb-4 text-right">Mai - Juillet <span class="text-primary">2014</span></td>
                <td class="pb-4 smaller">....</td>
                <td class="pb-4"><span class="text-danger">Infographiste</span> / <span class="text-danger">PAO</span> - Studio CG Designer à Narbonne (11)</td>
            </tr>
            <tr class="align-top">
                <td class="text-right">Septembre <span class="text-primary">2012</span> - Juillet <span class="text-primary">2013</span></td>
                <td class="smaller">....</td>
                <td>1ère année Bachelor Art et Multimedia - Studio M à Montpellier (34)</td>
            </tr>
            <tr class="align-top">
                <td class="text-right">Avril - Mai <span class="text-primary">2013</span></td>
                <td class="smaller">....</td>
                <td><span class="text-danger">Infographiste</span> / <span class="text-danger">Imprimeur Offset</span> - Créapub à Béziers (34)</td>
            </tr>
            <tr class="align-top">
                <td class="pb-4 text-right">Mars - Avril <span class="text-primary">2013</span></td>
                <td class="pb-4 smaller">....</td>
                <td class="pb-4"><span class="text-danger">Infographiste</span> - Com.Gaudry à Sérignan (34)</td>
            </tr>
            <tr class="align-top">
                <td class="text-right">Septembre <span class="text-primary">2010</span> - Juillet <span class="text-primary">2012</span></td>
                <td class="smaller">....</td>
                <td>Brevet des métiers d'art (BacPro Infographie) - Lycée Frédéric Mistral à Nîmes (30)</td>
            </tr>
            <tr class="align-top">
                <td class="text-right">Janvier - Mars <span class="text-primary">2012</span></td>
                <td class="smaller">....</td>
                <td><span class="text-danger">Infographiste</span> - Typ'offset à Béziers (34)</td>
            </tr>
            <tr class="align-top">
                <td colspan="2"></td>
                <td class="pb-4"><a href="diploma!!!!!!!!!!!!!!!!" onclick="window.open(this.href); return false;" class="link btn btn-info"><i class="fa fa-file"> | Brevet des métiers d'art</i></a></td>
            </tr>
            <tr class="align-top">
                <td class="text-right">Septembre <span class="text-primary">2008</span> - Juillet <span class="text-primary">2010</span></td>
                <td class="smaller">....</td>
                <td>CAP Sérigraphie industrielle - Lycée Frédéric Mistral à Nîmes (30)</td>
            </tr>
            <tr class="align-top">
                <td class="text-right">Janvier - Février <span class="text-primary">2010</span></td>
                <td class="smaller">....</td>
                <td><span class="text-danger">Sérigraphe</span> - Languedoc-roussillon publicité à Sauvian (34)</td>
            </tr>
            <tr class="align-top">
                <td class="text-right">Mai - Juin <span class="text-primary">2009</span></td>
                <td class="smaller">....</td>
                <td><span class="text-danger">Sérigraphe</span> - Vilar sérigraphie à Vendres (34)</td>
            </tr>
            <tr class="align-top">
                <td colspan="2"></td>
                <td><a href="diploma!!!!!!!!!!!!!!!!" onclick="window.open(this.href); return false;" class="link btn btn-info"><i class="fa fa-file"> | CAP Sérigraphie industrielle</i></a></td>
            </tr>
        </table>
    </main>

    <?php include_once './view/include/footer.html' ?>

</body>



</html>