<!DOCTYPE html>
<html lang="fr">

<head>
    <?php include_once('view/include/head.html'); ?>
    <title>Parcours professionnel et scolaire - Pierre Marquet</title>
</head>

<body>

    <?php include_once('view/include/nav.html'); ?>

    <main class="container bigtext">
        <h1 class="mb-5 text-center">Mon parcours professionnel et scolaire</h1>
        <table class="container-fluid">
            <tr class="align-top">
                <td class="text-right">Novembre 2019 - Juillet 2020</td>
                <td class="smaller">....</td>
                <td><i class="fas fa-graduation-cap"></i> Formation <strong>Développeur web et web mobile</strong> - AFPA de Balma (31)</td>
            </tr>
            <tr class="align-top">
                <td class="pb-4 text-right">Mai - Juillet 2020</td>
                <td class="pb-4 smaller">....</td>
                <td class="pb-4"><i class="fas fa-desktop"></i> <strong class="text-danger">Développeur web et web mobile</strong></td>
            </tr>
            <tr class="align-top">
                <td class="text-right">Septembre 2014 - Octobre 2019</td>
                <td class="smaller">....</td>
                <td><i class="fas fa-desktop"></i> <strong class="text-danger">Infographiste</strong> / <strong class="text-danger">Gendarme Adjoint volontaire</strong> - Centre de Production Multimédia de la GN à Limoges (31)</td>
            </tr>
            <tr class="align-top">
                <td colspan="2"></td>
                <td class="pb-4"><img src="./sources/files/logoGendarmerie.jpg" alt="Logo gendarmerie Nationale" width="200"></td>
            </tr>
            <tr class="align-top">
                <td class="text-right">Septembre 2013 - Juillet 2014</td>
                <td class="smaller">....</td>
                <td><i class="fas fa-graduation-cap"></i> 1ère année BTS <strong>Design d'espace et volume</strong> - Lycée J.F. Champollion à Montpellier (34)</td>
            </tr>
            <tr class="align-top">
                <td class="pb-4 text-right">Mai - Juillet 2014</td>
                <td class="pb-4 smaller">....</td>
                <td class="pb-4"><i class="fas fa-desktop"></i> <strong class="text-danger">Infographiste</strong> / <strong class="text-danger">PAO</strong> - Studio CG Designer à Narbonne (11)</td>
            </tr>
            <tr class="align-top">
                <td class="text-right">Septembre 2012 - Juillet 2013</td>
                <td class="smaller">....</td>
                <td><i class="fas fa-graduation-cap"></i> 1ère année Bachelor <strong>Art et Multimedia</strong> - Studio M à Montpellier (34)</td>
            </tr>
            <tr class="align-top">
                <td class="text-right">Avril - Mai 2013</td>
                <td class="smaller">....</td>
                <td><i class="fas fa-desktop"></i> <strong class="text-danger">Infographiste</strong> / <strong class="text-danger">Imprimeur Offset</strong> - Créapub à Béziers (34)</td>
            </tr>
            <tr class="align-top">
                <td class="pb-4 text-right">Mars - Avril 2013</td>
                <td class="pb-4 smaller">....</td>
                <td class="pb-4"><i class="fas fa-desktop"></i> <strong class="text-danger">Infographiste</strong> - Com.Gaudry à Sérignan (34)</td>
            </tr>
            <tr class="align-top">
                <td class="text-right">Septembre 2010 - Juillet 2012</td>
                <td class="smaller">....</td>
                <td><i class="fas fa-graduation-cap"></i> Brevet des <strong>métiers d'art</strong> (BacPro <strong>Infographie</strong>) - Lycée Frédéric Mistral à Nîmes (30)</td>
            </tr>
            <tr class="align-top">
                <td class="pb-4 text-right">Janvier - Mars 2012</td>
                <td class="pb-4 smaller">....</td>
                <td class="pb-4"><i class="fas fa-desktop"></i> <strong class="text-danger">Infographiste</strong> - Typ'offset à Béziers (34)</td>
            </tr>
            <tr class="align-top">
                <td class="text-right">Septembre 2008 - Juillet 2010</td>
                <td class="smaller">....</td>
                <td><i class="fas fa-graduation-cap"></i> CAP <strong>Sérigraphie industrielle</strong> - Lycée Frédéric Mistral à Nîmes (30)</td>
            </tr>
            <tr class="align-top">
                <td class="text-right">Janvier - Février 2010</td>
                <td class="smaller">....</td>
                <td><i class="fas fa-desktop"></i> <strong class="text-danger">Sérigraphe</strong> - Languedoc-roussillon publicité à Sauvian (34)</td>
            </tr>
            <tr class="align-top">
                <td class="text-right">Mai - Juin 2009</td>
                <td class="smaller">....</td>
                <td><i class="fas fa-desktop"></i> <strong class="text-danger">Sérigraphe</strong> - Vilar sérigraphie à Vendres (34)</td>
            </tr>
        </table>
    </main>

    <?php include_once('view/include/footer.html'); ?>

</body>



</html>