<!DOCTYPE html>
<html lang="fr">

<head>
    <?php include_once './view/include/head.html' ?>
    <script src="./library/js/age.js"></script>
</head>

<body>

    <?php include_once './view/include/nav.html' ?>

    <main class="container">
        <h1 class="mb-5 text-center">Qui suis-je ?</h1>
        <div class="profile">
            <img class="rounded-circle" src="./sources/files/profile.jpg" alt="Moi" width="200" height="200">
            <div class="ml-5 mr-5">
                <h2>Pierre Marquet</h2>
                <h4 id="myAge">Mon Age</h4>
                <h6>marquet_pierre@yahoo.fr</h6>
            </div>
            <img src="./sources/files/logoBl.png" alt="Mon logo" class="todisappear" height="200">
        </div>
        <div class="mt-3">
            <p class="text-justify">
                Inter quos Paulus eminebat notarius ortus in Hispania, glabro quidam sub vultu latens, odorandi vias
                periculorum occultas perquam sagax. is in Brittanniam missus ut militares quosdam perduceret ausos
                ingenuorum adfligens et quosdam obterens manicis, crimina scilicet multa consarcinando a veritate
                longe
                discreta. unde admissum est facinus impium, quod Constanti tempus nota inusserat sempiterna.
            </p>
        </div>
        <div class="d-flex flex-wrap justify-content-center">
            <a href="https://www.linkedin.com/in/pierre-marquet-98987b199/" onclick="window.open(this.href); return false;" class="link btn btn-primary btn-lg"><i class="fa fa-linkedin"> | Voir mon linkedin</i></a>
            <a href="https://github.com/SokouPM" onclick="window.open(this.href); return false;" class="link btn btn-secondary btn-lg "><i class="fa fa-github"> | Voir mon github</i></a>
            <a href="mailto:marquet_pierre@yahoo.fr" class="link btn btn-danger btn-lg"><i class="fa fa-envelope">
                    | Contactez-moi</i></a>
            <a href="./sources/files/CV_PierreMarquet.pdf" onclick="window.open(this.href); return false;" class="link btn btn-success btn-lg"><i class="fa fa-file"> | Téléchargez mon CV</i></a>
        </div>

        <div id="carouselSlide" class="carousel slide mt-5" data-ride="carousel">
            <ul class="carousel-indicators">
                <li data-target="#carouselSlide" data-slide-to="0" class="active"></li>
                <li data-target="#carouselSlide" data-slide-to="1"></li>
                <li data-target="#carouselSlide" data-slide-to="2"></li>
                <li data-target="#carouselSlide" data-slide-to="3"></li>
            </ul>
            <!-- carousel pictures -->
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="./sources/carousel/1.png" alt="Missing pic :/" width="100%" height="600">
                </div>
                <div class="carousel-item">
                    <img src="./sources/carousel/2.png" alt="Missing pic :/" width="100%" height="600">
                </div>
                <div class="carousel-item">
                    <img src="./sources/carousel/3.png" alt="Missing pic :/" width="100%" height="600">
                </div>
                <div class="carousel-item">
                    <img src="./sources/carousel/4.png" alt="Missing pic :/" width="100%" height="600">
                </div>
            </div>
            <!-- carousel controls -->
            <a class="carousel-control-prev" href="#carouselSlide" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#carouselSlide" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>

    </main>

    <?php include_once './view/include/footer.html' ?>

</body>

</html>