<!DOCTYPE html>
<html lang="fr">

<head>
    <?php include_once('view/include/head.html'); ?>
    <?php if ($_SESSION["snow"] === true) : ?>
        <script type="text/javascript" src="./library/js/snow.js"></script>
    <?php endif ?>
    <title>Développeur Web, Infographiste sur Paris - Pierre Marquet</title>
</head>

<body>

    <?php include_once('view/include/nav.html'); ?>

    <main class="container">
        <div class="profile">
            <img class="rounded-circle" id="profilePicture" src="./sources/files/profile.jpg" alt="Pierre Marquet" width="200" height="200">
            <div class="ml-5 mr-5">
                <h2 id="name">Pierre Marquet</h2>
                <h1 id="job">Infographiste / Développeur Web</h1>
                <h3><i class="fas fa-map-marker-alt"></i> Paris</h3>
            </div>
            <img src="./sources/files/logoBl.png" alt="Infographie logo" class="todisappear" id="logo" height="200">
        </div>
        <div class="mt-3">
            <p id="presentation" class="text-justify text-dark">
                Issu du monde de l'<strong>infographie</strong>, j'ai travaillé pendant 5 ans pour la <strong>Gendarmerie Nationale</strong> afin de mettre en forme des parcours d'enseignements à travers l'<strong>image</strong> et l'<strong>animation</strong>. je me suis ensuite formé au métier de <strong>développeur web</strong> pour travailler dans un domaine qui me passionne et devenir plus polyvalent.
            </p>
        </div>
        <div class="d-flex flex-wrap justify-content-center">
            <a href="https://www.linkedin.com/in/pierre-marquet-98987b199/" onclick="window.open(this.href); return false;" class="link btn btn-primary btn-lg"><i class="fab fa-linkedin-in"></i> | Voir mon linkedin</a>
            <a href="https://github.com/SokouPM" onclick="window.open(this.href); return false;" class="link btn btn-secondary btn-lg "><i class="fab fa-github"></i> | Voir mon github</a>
            <a href="index.php?contact" class="link btn btn-danger btn-lg"><i class="fa fa-envelope"></i> | Contactez-moi</a>
            <a href="./sources/files/CV_PierreMarquet.pdf" onclick="window.open(this.href); return false;" class="link btn btn-success btn-lg"><i class="fas fa-file-pdf"></i> | Téléchargez mon CV</a>
        </div>

        <!-- carousel -->
        <div id="carouselSlide" class="carousel slide mt-5" data-ride="carousel">
            <ul class="carousel-indicators">
                <li data-target="#carouselSlide" data-slide-to="0" class="active"></li>
                <li data-target="#carouselSlide" data-slide-to="1"></li>
                <li data-target="#carouselSlide" data-slide-to="2"></li>
                <li data-target="#carouselSlide" data-slide-to="3"></li>
            </ul>
            <!-- carousel pictures -->
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="./sources/carousel/1.png" alt="site web teamrocket" width="100%" height="600">
                </div>
                <div class="carousel-item">
                    <img src="./sources/carousel/2.png" alt="infographie jaquette" width="100%" height="600">
                </div>
                <div class="carousel-item">
                    <img src="./sources/carousel/3.png" alt="infographie livret" width="100%" height="600">
                </div>
                <div class="carousel-item">
                    <img src="./sources/carousel/4.png" alt="photomontage" width="100%" height="600">
                </div>
            </div>
            <!-- carousel controls -->
            <a class="carousel-control-prev" href="#carouselSlide" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#carouselSlide" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>

    </main>

    <?php include_once('view/include/footer.html'); ?>

</body>

</html>